tracker/urls.py
from django.urls import path

from tracker.views import (
    index,
    VaccineListView,
    ChildListView,
    ChildDetailView,
    VaccinationDetailView,
    ChildCreateView,
    ChildUpdateView,
    ChildDeleteView,
    ComplicationListView,
    VaccinationCreateView,
    VaccinationUpdateView,
    VaccinationDeleteView,
    ComplicationCreateView,
    ComplicationUpdateView,
    ComplicationDeleteView,
    ParentCreateView,
    ParentDetailView,
)

urlpatterns = [
    path("", index, name="index"),
    path("schedule/", VaccineListView.as_view(), name="vaccine-list"),
    path("children/", ChildListView.as_view(), name="child-list"),
    path("children/<int:pk>/", ChildDetailView.as_view(), name="child-detail"),
    path("children/create/", ChildCreateView.as_view(), name="child-create"),
    path(
        "children/<int:pk>/update/",
        ChildUpdateView.as_view(),
        name="child-update",
    ),
    path(
        "children/<int:pk>/delete/",
        ChildDeleteView.as_view(),
        name="child-delete",
    ),
    path(
        "vaccination/<int:pk>/",
        VaccinationDetailView.as_view(),
        name="vaccination-detail",
    ),
    path(
        "children/<int:pk>/vaccination/create/",
        VaccinationCreateView.as_view(),
        name="vaccination-create",
    ),
    path(
        "vaccination/<int:pk>/update/",
        VaccinationUpdateView.as_view(),
        name="vaccination-update",
    ),
    path(
        "children/<int:c_id>/vaccination/<int:pk>/delete/",
        VaccinationDeleteView.as_view(),
        name="vaccination-delete",
    ),
    path(
        "complication/",
        ComplicationListView.as_view(),
        name="complication-list",
    ),
    path(
        "vaccination/<int:pk>/complication/create/",
        ComplicationCreateView.as_view(),
        name="complication-create",
    ),
    path(
        "complication/<int:pk>/update/",
        ComplicationUpdateView.as_view(),
        name="complication-update",
    ),
    path(
        "complication/<int:pk>/delete/",
        ComplicationDeleteView.as_view(),
        name="complication-delete",
    ),
    path("parent/create/", ParentCreateView.as_view(), name="parent-create"),
    path("parent/<int:pk>/", ParentDetailView.as_view(), name="parent-detail"),
]

app_name = "tracker"

vaccination_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tracker.urls", namespace="tracker")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


tracker/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from vaccination_tracker import settings


class Parent(AbstractUser):
    pass


class Child(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    gender = models.CharField(max_length=50)
    birth_date = models.DateField()
    parent = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        related_name="children",
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name_plural = "children"
        ordering = ["birth_date"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Vaccine(models.Model):
    name = models.CharField(max_length=50, unique=True)
    number_of_doses = models.IntegerField(default=1)
    age_for_first_dose_days = models.IntegerField(default=0)

    class Meta:
        ordering = ["age_for_first_dose_days"]

    def __str__(self):
        return self.name


class Vaccination(models.Model):
    vaccine = models.ForeignKey(
        to=Vaccine, related_name="vaccines", on_delete=models.CASCADE
    )
    child = models.ForeignKey(
        to=Child, on_delete=models.CASCADE, related_name="vaccinations"
    )
    date_vaccination = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ["date_vaccination"]

    def __str__(self):
        return f"{self.vaccine} for {self.child}"


class Complication(models.Model):
    description = models.CharField(max_length=50)
    date_occurrence = models.DateTimeField(auto_now_add=True)
    vaccination = models.ForeignKey(
        to=Vaccination, related_name="complications", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.description

tracker/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Field
from django import forms
from django.contrib.auth.forms import UserCreationForm

from tracker.models import Vaccination, Complication, Parent, Vaccine


class VaccinationCreateForm(forms.ModelForm):
    vaccine = forms.ModelChoiceField(queryset=Vaccine.objects.all())

    class Meta:
        model = Vaccination
        fields = ['vaccine']


class ComplicationCreateForm(forms.ModelForm):
    class Meta:
        model = Complication
        fields = ["description"]


class ParentCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Parent
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
        )

tracker/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic

from tracker.forms import (
    VaccinationCreateForm,
    ComplicationCreateForm,
    ParentCreationForm,
)
from tracker.models import Child, Parent, Vaccine, Vaccination, Complication
from tracker.utils import get_referer, get_vaccine_id_from_url


def index(request):
    num_children = Child.objects.count()
    num_parents = Parent.objects.count()
    num_complications = Complication.objects.count()

    context = {
        "num_children": num_children,
        "num_parents": num_parents,
        "num_complications": num_complications,
    }

    return render(request, "tracker/index.html", context=context)


class VaccineListView(LoginRequiredMixin, generic.ListView):
    model = Vaccine
    queryset = Vaccine.objects.all()
    template_name = "tracker/vaccine_list.html"


class ChildListView(LoginRequiredMixin, generic.ListView):
    model = Child
    queryset = Child.objects.prefetch_related("vaccinations__vaccine")
    template_name = "tracker/child_list.html"


class ChildDetailView(LoginRequiredMixin, generic.DetailView):
    model = Child
    queryset = Child.objects.prefetch_related("vaccinations")
    template_name = "tracker/child_detail.html"


class ChildCreateView(LoginRequiredMixin, generic.CreateView):
    model = Child
    fields = ("first_name", "last_name", "gender", "birth_date")
    success_url = reverse_lazy("tracker:child-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["previous_url"] = get_referer(self.request)
        return context

    def form_valid(self, form):
        form.instance.parent = self.request.user
        return super().form_valid(form)


class ChildUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Child
    fields = ("first_name", "last_name", "gender", "birth_date")
    success_url = reverse_lazy("tracker:child-list")


class ChildDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Child
    success_url = reverse_lazy("tracker:child-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["previous_url"] = get_referer(self.request)
        return context


class VaccinationDetailView(LoginRequiredMixin, generic.DetailView):
    model = Vaccination
    template_name = "tracker/vaccination_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["previous_url"] = get_referer(self.request)
        return context


class VaccinationCreateView(LoginRequiredMixin, generic.CreateView):
    model = Vaccination
    form_class = VaccinationCreateForm

    def get(self, request, *args, **kwargs):
        kwargs["child_id"] = self.kwargs.get("pk")
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        child = get_object_or_404(Child, pk=self.kwargs["pk"])
        form.instance.child = child
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["previous_url"] = get_referer(self.request)
        return context

    def get_success_url(self, **kwargs):
        return reverse(
            "tracker:child-detail", kwargs={"pk": self.kwargs["pk"]}
        )


class VaccinationUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Vaccination
    fields = ("vaccine",)

    def get_success_url(self, **kwargs):
        return reverse(
            "tracker:vaccination-detail", kwargs={"pk": self.kwargs["pk"]}
        )


class VaccinationDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Vaccination

    def get_success_url(self, **kwargs):
        return reverse(
            "tracker:child-detail", kwargs={"pk": self.kwargs["c_id"]}
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["previous_url"] = get_referer(self.request)
        return context


class ComplicationListView(LoginRequiredMixin, generic.ListView):
    model = Complication
    template_name = "tracker/complication_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["previous_url"] = get_referer(self.request)
        context["vaccine_id"] = get_vaccine_id_from_url(context["previous_url"])
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        reference = get_referer(self.request)
        some_value = get_vaccine_id_from_url(reference)
        if some_value:
            queryset = queryset.filter(vaccination_id=some_value)
        return queryset


class ComplicationCreateView(LoginRequiredMixin, generic.CreateView):
    model = Complication
    form_class = ComplicationCreateForm
    success_url = reverse_lazy("tracker:complication-list")

    def form_valid(self, form):
        vaccination = get_object_or_404(Vaccination, pk=self.kwargs["pk"])
        form.instance.vaccination = vaccination
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["previous_url"] = get_referer(self.request)
        return context


class ComplicationUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Complication
    fields = ("description",)
    success_url = reverse_lazy("tracker:complication-list")


class ComplicationDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Complication
    success_url = reverse_lazy("tracker:complication-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["previous_url"] = get_referer(self.request)
        return context


class ParentCreateView(generic.CreateView):
    model = Parent
    form_class = ParentCreationForm
    success_url = reverse_lazy("tracker:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        parent = authenticate(
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password1"],
        )
        login(self.request, parent)
        messages.success(
            self.request, "Thanks for registering. You are now logged in."
        )
        return response


class ParentDetailView(LoginRequiredMixin, generic.DetailView):
    model = Parent
    template_name = "tracker/parent_detail.html"

    def get_success_url(self, **kwargs):
        return reverse(
            "tracker:parent-detail", kwargs={"pk": self.kwargs["pk"]}
        )

templates/tracker/child_confirm_delete.html
{% extends "base_background.html" %}

{% block content %}
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
    <div class="container-fluid py-2">
      <h1>Delete information about child?</h1>
      <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes" class="btn btn-danger">
        <a class="btn btn-primary" href="{{ previous_url }}">Cancel</a>
      </form>
      <p>After deleting you cant access  any information.</p>
      <p>We are sorry that you did not like our service.</p>
    </div>
  </div>
{% endblock %}

templates/tracker/child_detail.html
{% extends "base_background.html" %}

{% load static %}
{% load compare_date %}
{% load calculate_date %}

{% block content %}
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
  <section class="py-sm-1 py-1 position-relative">
    <div class="container">
      <div class="row justify-content-center mb-4">
        <div class="col-md-7 col-12 mb-4 mb-md-0">
          <h3 class="text-center mb-2">Name: {{ child.first_name }} {{ child.last_name }}</h3>
           <div class="d-flex justify-content-center">
            <a href="{% url 'tracker:child-delete' pk=child.id %}" class="btn btn-secondary link-to-page me-2">Delete information</a>
            <a href="{% url 'tracker:child-update' pk=child.id %}" class="btn btn-secondary link-to-page">Update information</a>
          </div>

        </div>
        <div class="col-md-5 col-12">
          <h3 class="text-center mb-2">{{ child.first_name }} received new vaccination?</h3>
          <div class="d-flex justify-content-center">
            <a href="{% url 'tracker:vaccination-create' pk=child.id %}" class="btn btn-primary">Add vaccination</a>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

      {% if child.vaccinations.all %}
        <div class="btn-block bg-gray-600">
          <h3 style="text-align: center">Vaccine that {{ child.first_name }} already received</h3>
        </div>
        <div class="container-fluid">
          <table class="table">
            <thead>
            <tr>
              <th>Name(Click on vaccine name to find out more)</th>
              <th>Recommended date</th>
              <th>Actual date</th>
              <th>Timing</th>
            </tr>
            </thead>
            <tbody>
            {% for vaccination in child.vaccinations.all %}
              <tr>
                <td>
                  <a class="badge bg-success" href="{% url 'tracker:vaccination-detail' vaccination.id %}">
                    {{ vaccination.vaccine }}
                  </a>
                </td>
                <td>{% calculate_date child.birth_date vaccination.vaccine.age_for_first_dose_days %}</td>
                <td>{{ vaccination.date_vaccination }}</td>
                <td>{% compare_date child.birth_date vaccination.vaccine.age_for_first_dose_days vaccination.date_vaccination %}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>

        </div>
      {% endif %}
    </section>
  </div>
{% endblock %}

templates/tracker/child_form.html
{% extends "base_background.html" %}
{% load crispy_forms_filters %}
{% load add_class %}

{% block content %}


<div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
   <div class="container-fluid py-2">
     <h1>{{ object|yesno:"Update,Add" }} child information</h1>
     <form  action="" method="post" novalidate>

        {% csrf_token %}
       {{ form|crispy}}
       <div style="display: flex;">
  <button type="submit" class="btn btn-behance m-2">Save</button>
      <a class="btn btn-primary m-2" href="{% url 'tracker:child-list' %}">Cancel</a>
        </div>
     </form>

    </div>
  </div>
{% endblock %}


templates/tracker/child_list.html
{% extends "base_background.html" %}
{% load static %}
{% block content %}

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
    <section class="py-sm-1 py-1 position-relative">
      <div class="container">
        {% if user.children.all %}
         <h4> Information about your children</h4>
          <div class="container-fluid">
          <p class="badge bg-success">Click on id to find more information</p>
          <table class="table">
            <tr>
              <th>ID</th>
              <th>First name</th>
              <th>Last name</th>
              <th>Birth date</th>
              <th>Number of completed vaccine</th>
            </tr>
            {% for child in child_list %}
              {% if child.parent == user %}
                <tr>
                  <td><a href="{% url 'tracker:child-detail' pk=child.id %}"><p
                      class="badge bg-success">{{ child.id }}</p></a></td>
                  <td>{{ child.first_name }}</td>
                  <td>{{ child.last_name }}</td>
                  <td>{{ child.birth_date }}</td>
                  <td>{{ child.vaccinations.count }}</td>
                </tr>
              {% endif %}
            {% endfor %}
          </table>
          <a href="{% url 'tracker:child-create' %}" class="btn btn-primary link-to-page"> Add child</a>
        {% else %}
          <div class="container-fluid">
            <h4>You not registered children on this site</h4>
            <p>Click on button and fill in information about your child</p>
            <a href="{% url 'tracker:child-create' %}" class="btn btn-primary link-to-page"> Add child</a>
            <p>Good luck!</p>
            <p>Thank you for joining us</p>
          </div>
        {% endif %}
        </div>
      </div>
  </section>
  </div>
{% endblock %}

templates/tracker/complication_confirm_delete.html
{% extends "base_background.html" %}

{% block content %}
  <h1>Delete complication?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-primary" href="{{ previous_url }}">Cancel</a>
  </form>
{% endblock %}

templates/tracker/complication_form.html
{% extends "base_background.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
    <div class="container-fluid py-2">
      <h1>{{ object|yesno:"Update,Create" }} complication</h1>
      <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <div style="display: flex;">
          <button type="submit" class="btn btn-behance m-2">Save</button>
          <a class="btn btn-primary m-2" href="{{ previous_url }}">Go back</a>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

templates/tracker/complication_list.html
{% extends "base_background.html" %}
{% load static %}

{% block content %}
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">

    <section class="py-sm-1 py-1 position-relative">
      <div class="container">
        <div class="row">
          <div class="col-6 mx-auto">
            <div class="row py-5">
              <h3>Complication</h3>
              <h6>Soreness where the shot is given or fever can happen after vaccination.</h6>
              <div class="container-fluid"></div>
              {% if complication_list %}
                <table class="table">
                  <tr>
                    <th>ID</th>
                    <th>Decsription</th>
                    <th>Time when occured</th>
                    <th>After vaccine</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </tr>
                  {% for complication in complication_list %}
                    <tr>
                      <td>
                        {{ complication.id }}
                      </td>
                      <td>
                        {{ complication.description }}
                      </td>
                      <td>
                        {{ complication.date_occurrence }}
                      </td>
                      <td>
                        {{ complication.vaccination }}
                      </td>
                      <td>
                        <a href="{% url "tracker:complication-update" pk=complication.id %}">UPDATE</a>
                      </td>
                      <td>
                        <a href="{% url "tracker:complication-delete" pk=complication.id %}">DELETE</a>
                      </td>
                    </tr>
                  {% endfor %}
                </table>
              {% else %}
                <p>No complication happened after vaccination</p>
              {% endif %}
            </div>
            <a href="{% url 'tracker:vaccination-detail' vaccine_id %}" class="btn btn-secondary link-to-page">Go
              back</a>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock %}


templates/tracker/index.html
{% extends "base_background.html" %}

{% load static %}

{% block title %} Vaccine tracker {% endblock title %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block content %}

<div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">

<section class="pt-3 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 mx-auto py-3">
        <div class="row">
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary"><span id="state1" countTo={{ num_parents }}>0</span>+</h1>
              <h5 class="mt-3">Parents</h5>
              <p class="text-sm font-weight-normal">Using our app to keep up with vaccination calendar</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary"> <span id="state2" countTo={{ num_children }}>0</span>+</h1>
              <h5 class="mt-3">Children</h5>
              <p class="text-sm font-weight-normal">Taked care of with our help</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary" id="state3" countTo={{ num_complications }}>0</h1>
              <h5 class="mt-3">Complications</h5>
              <p class="text-sm font-weight-normal">Was observed through our app</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 ms-auto">
        <h4 class="mb-1">Thank you for your visiting!</h4>
        <p class="lead mb-0">We care about you!</p>
      </div>
      <div class="col-lg-5 me-lg-auto my-lg-auto text-lg-end mt-5">
        <a href="https://twitter.com/intent/tweet?text=Check%20Material%20UI%20Kit%20made%20by%20%40CreativeTim%20%23webdesign%20%23designsystem%20%23bootstrap5&url=https%3A%2F%2Fwww.creative-tim.com%2Fproduct%2Fmaterial-kit" class="btn btn-twitter mb-0 me-2" target="_blank">
          <i class="fab fa-twitter me-1"></i> Tweet
        </a>
        <a href="https://www.facebook.com/sharer/sharer.php?u=https://appseed.us/product/material-kit/django/" class="btn btn-facebook mb-0 me-2" target="_blank">
          <i class="fab fa-facebook-square me-1"></i> Share
        </a>
        <a href="https://www.pinterest.com/pin/create/button/?url=https://appseed.us/product/material-kit/django/" class="btn btn-pinterest mb-0 me-2" target="_blank">
          <i class="fab fa-pinterest me-1"></i> Pin it
        </a>
      </div>
    </div>
  </div>
</div>

</div>

{% endblock content %}

{% block javascripts %}

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{% static 'js/plugins/countup.min.js' %}"></script>
<script src="{% static 'js/plugins/choices.min.js' %}"></script>
<script src="{% static 'js/plugins/prism.min.js' %}"></script>
<script src="{% static 'js/plugins/highlight.min.js' %}"></script>
<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{% static 'js/plugins/rellax.min.js' %}"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{% static 'js/plugins/tilt.min.js' %}"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{% static 'js/plugins/choices.min.js' %}"></script>


<script type="text/javascript">

  if (document.getElementById('state1')) {
    const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
    if (!countUp.error) {
      countUp.start();
    } else {
      console.error(countUp.error);
    }
  }
  if (document.getElementById('state2')) {
    const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
    if (!countUp1.error) {
      countUp1.start();
    } else {
      console.error(countUp1.error);
    }
  }
  if (document.getElementById('state3')) {
    const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
    if (!countUp2.error) {
      countUp2.start();
    } else {
      console.error(countUp2.error);
    };
  }
</script>

{% endblock javascripts %}

templates/tracker/vaccination_confirm_delete.html
{% extends "base_background.html" %}

{% block content %}
  <h1>Delete vaccination?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-primary" href="{{ previous_url }}">Cancel</a>
  </form>
{% endblock %}

templates/tracker/vaccination_detail.html
{% extends "base_background.html" %}
{% load static %}
{% block content %}

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">

    <section class="py-sm-2 py-0 position-relative">
      <div class="container">
        <div class="row">
          <section class="py-2">
            <div class="container py-3">
              <div class="row align-items-center">
                <div class="col-lg-6">
                  <div class="row justify-content-start">
                    <div class="col-md-6">
                      <div class="info">
                        <i class="material-icons text-3xl text-gradient text-info mb-3">public</i>
                        <h5>Vaccine</h5>
                        <p>{{ vaccination.vaccine }}</p>
                        <a href="{% url "tracker:vaccination-update" pk=vaccination.id %}"
                           class="btn btn-primary link-to-page">UPDATE</a>
                        <a href="{% url "tracker:vaccination-delete" c_id=vaccination.child_id pk=vaccination.id %}"
                           class="btn btn-secondary link-to-page">DELETE</a>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="info">
                        <i class="material-icons text-3xl text-gradient text-info mb-3">payments</i>
                        <h5>Number of side effects</h5>
                        <p>{{ vaccination.complications.count }}</p>
                        <a href="{% url 'tracker:complication-create'  pk=vaccination.id %}"
                           class="btn btn-dark link-to-page">
                          Add more
                        </a>
                      </div>
                    </div>
                  </div>
                  <div class="row justify-content-start mt-4">
                    <div class="col-md-6">
                      <div class="info">
                        <i class="material-icons text-3xl text-gradient text-info mb-3">apps</i>
                        <h5>Time</h5>
                        <p>{{ vaccination.date_vaccination }}</p>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="info">
                        <i class="material-icons text-3xl text-gradient text-info mb-3">3p</i>
                        <h5>Child</h5>
                        <p> {{ vaccination.child }} </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 ms-auto mt-lg-1 mt-3">
                  <div class="card-header p-3 position-relative mt-n4 mx-0 z-index-2">
                    <a class="d-block blur-shadow-image py-1">
                      <img
                          src="https://i0.wp.com/calmatters.org/wp-content/uploads/2022/06/062122-COVID-Vaccine-Children-CM-01.jpg?resize=1536%2C1024&ssl=1"
                          alt="img-colored-shadow" class="img-fluid border-radius-sm">
                    </a>
                    <div class="card-body text-center">
                      <h5 class="font-weight-normal">
                        <a href="javascript:;">More information about side effects</a>
                      </h5>
                      <a href="{% url 'tracker:complication-list' %}" class="btn btn-primary btn-block"> Click</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
  </div>
  </section>

{% endblock %}


templates/tracker/vaccination_form.html
{% extends "base_background.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
    <section class="py-sm-7 py-5 position-relative">
      <div class="container">
        <div class="row py-5">
          <h1>{{ object|yesno:"Update,Create" }} vaccination</h1>
          <form action="" method="post" novalidate class=>
            {% csrf_token %}
            {{ form|crispy }}

            <div style="display: flex;">
              <button type="submit" class="btn btn-primary m-2">Save</button>
<button class="btn btn-behance m-2 p-2" href="{{ previous_url }}">To vaccination list</button>
            </div>
          </form>

        </div>
      </div>
    </section>
  </div>
{% endblock %}