tracker/urls.py
from django.urls import path

from tracker.views import (
    index,
    VaccineListView,
    ChildListView,
    ChildDetailView,
    VaccinationDetailView,
    ChildCreateView,
    ChildUpdateView,
    ChildDeleteView,
    ComplicationListView,
    VaccinationCreateView,
    VaccinationUpdateView,
    VaccinationDeleteView,
    ComplicationCreateView,
    ComplicationUpdateView,
    ComplicationDeleteView,
    ParentCreateView,
    ParentDetailView,
)

urlpatterns = [
    path("", index, name="index"),
    path("schedule/", VaccineListView.as_view(), name="vaccine-list"),
    path("children/", ChildListView.as_view(), name="child-list"),
    path("children/<int:pk>/", ChildDetailView.as_view(), name="child-detail"),
    path("children/create/", ChildCreateView.as_view(), name="child-create"),
    path(
        "children/<int:pk>/update/",
        ChildUpdateView.as_view(),
        name="child-update",
    ),
    path(
        "children/<int:pk>/delete/",
        ChildDeleteView.as_view(),
        name="child-delete",
    ),
    path(
        "vaccination/<int:pk>/",
        VaccinationDetailView.as_view(),
        name="vaccination-detail",
    ),
    path(
        "children/<int:pk>/vaccination/create/",
        VaccinationCreateView.as_view(),
        name="vaccination-create",
    ),
    path(
        "vaccination/<int:pk>/update/",
        VaccinationUpdateView.as_view(),
        name="vaccination-update",
    ),
    path(
        "children/<int:c_id>/vaccination/<int:pk>/delete/",
        VaccinationDeleteView.as_view(),
        name="vaccination-delete",
    ),
    path(
        "complication/",
        ComplicationListView.as_view(),
        name="complication-list",
    ),
    path(
        "vaccination/<int:pk>/complication/create/",
        ComplicationCreateView.as_view(),
        name="complication-create",
    ),
    path(
        "complication/<int:pk>/update/",
        ComplicationUpdateView.as_view(),
        name="complication-update",
    ),
    path(
        "complication/<int:pk>/delete/",
        ComplicationDeleteView.as_view(),
        name="complication-delete",
    ),
    path("parent/create/", ParentCreateView.as_view(), name="parent-create"),
    path("parent/<int:pk>/", ParentDetailView.as_view(), name="parent-detail"),
]

app_name = "tracker"

vaccination_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tracker.urls", namespace="tracker")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


templates/includes/footer.html
<footer class="text-center text-white" style="background-color: #f1f1f1;">
  <div class="container pt-4">
    <section class="mb-4">

    </section>
  </div>
  <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    <p class="text-dark"> © 2023 Copyright: Vaccine tracker</p>
  </div>
</footer>

templates/includes/header.html
{% load static %}
<header class="header-2">
  <div class="page-header min-vh-45 relative" style="background-image: url('{% static 'img/virus mutations_large.jpg' %}')">
    <span class="mask bg-gradient-primary opacity-4"></span>
    <div class="container header-container">
      <div class="row">
        <div class="col-lg-7 text-center mx-auto header-text">
          <h1 class="text-bg-dark border-radius-2xl pt-3 mt-n5">Welcome to vaccination tracker</h1>
        </div>
      </div>
    </div>
  </div>
</header>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'tracker:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href={% url 'tracker:vaccine-list' %}>All vaccine</a>
      </li>
    </ul>
  </div>
</nav>

templates/includes/navigation.html
<nav class="navbar navbar-expand-lg navbar-purple">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  {% if user.is_authenticated %}
    <form class="form-inline">
    <button class="btn btn-outline-success" type="button"><a href="{% url 'tracker:parent-detail' pk=user.id %}">{{ user.username }}</a></button>
    <button class="btn btn-outline-success" type="button"><a href="{% url 'logout' %}">Log out</a></button>
  {% else %}
    <button class="btn btn-outline-success" type="button"><a href="{% url 'login' %}">Log in</a></button>
    <button class="btn btn-outline-success"  type="button"><a href="{% url 'tracker:parent-create' %}">Create an account</a></button>
  {% endif %}
  </form>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <button class="btn btn-link" type="button"><a class="nav-item nav-link active" href="{% url 'tracker:index' %}">Home</a></button>
      <button class="btn btn-link" type="button"><a class="nav-item nav-link" href="{% url 'tracker:child-list' %}">Children</a></button>
      <button class="btn btn-link" type="button"><a class="nav-item nav-link" href="{% url 'tracker:vaccine-list' %}">Vaccination calendar</a></button>
    </div>
  </div>
</nav>

templates/includes/scripts.html
  {% load static %}

  <!--   Core JS Files   -->
  <script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
  <script src="{% static 'js/plugins/parallax.min.js' %}"></script>
  <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{% static 'js/material-kit.min.js' %}" type="text/javascript"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
{% if user.is_authenticated %}
    <p>User: {{ user.username }}</p>
{# <a href="{% url "tracker:parent-detail" pk=user.id %}"#}
    <p class="button alert-danger"><a href="{% url 'logout' %}">Log out</a></p>
  {% else %}
    <p class="button"><a href="{% url 'login' %}">Log in</a></p>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'tracker:child-list' %}">Children</a></li>
</ul>